### ISSUE TITLE
Feature Request: OpenAlias

### ISSUE THREAD

**Issue by reemuru** [monerochan-moe/monerochanradio#3]
Add openalias support for monerochan.moe tipping for funding new features.

sample dns entry:

TXT

```bash
"oa1:xmr recipient_address=4xxx; recipient_name=MoneroChanRadio; tx_description=Donate to MoneroChanRadio!;"
```

reference: https://web.getmonero.org/resources/moneropedia/openalias.html

**Comment by monerochan-moe** [comment]
Hi thanks for your interest.
No donations or tips accepted.
However, you could help with the following
- Donate to https://moneroart.neocities.org/ for more art
- Help code the newest feature: Interactive volleyballs on the Monerochan Radio Beach theme https://github.com/monerochan-moe/monerochanradio/tree/interactive-volleyballs

**Comment by reemuru** [comment]
Sure, will check out contributing some code. Thanks
